[package]
name = "printers_ffi"
version = "1.0.0"
authors = ["Tales Luna <tales.ferreira.luna@gmail.com>"]

[dependencies]
libc = "0.2"

[dependencies.printers]
path = "../"
# printers = "2.0"

[lib]
name = "printers_fii"
path = "lib.rs"
bench = false
crate-type = ["cdylib"]
